name: Build Push and Deploy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build-and-push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # - name: Build docker image
      #   # we are using dev docker file because we need to run test at first
      #   # we just need to run test on client docker image so we only need to created that image as of now
      #   run: docker build -t nishanprime/client -f ./client/Dockerfile.dev ./client

      # - name: Run test
      #   run: docker run -e CI=true nishanprime/client npm run test

      # - name: Build docker prod images
      #   run: |
      #     docker build -t nishanprime/client ./client
      #     docker build -t nishanprime/server ./server
      #     docker build -t nishanprime/worker ./worker
      #     docker build -t nishanprime/nginx ./nginx

      # - name: Docker Login
      #   env:
      #     DOCKER_USER: ${{secrets.DOCKER_USER}}
      #     DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      #   run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      # - name: Docker Push
      #   run: |
      #     docker push nishanprime/client
      #     docker push nishanprime/server
      #     docker push nishanprime/worker
      #     docker push nishanprime/nginx

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: '${{ steps.current-time.outputs.time }}'
          replace-with: '-'
          flags: 'g'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: multi-docker-practice
          environment_name: Multidockerpractice-env
          version_label: 'Sample Application'
          region: us-east-2
          existing_bucket_name: elasticbeanstalk-us-east-2-410333440162
